dist: trusty
sudo: required
language: php

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
      - redis-server-3.2
      - redis-client-3.2

php:
  - '7.0'

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  on_success: never
  on_failure: always

before_script:
  - mysql -u root -e 'create database hello_world_test; use hello_world_test;'

before_install: phpenv config-add phpconfig.ini

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml
