dist: trusty
sudo: required
language: php

php:
  - '7.0'

services:
  - mysql
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  on_success: never
  on_failure: always

before_script:
  - mysql -u travis -e 'create database hello_world_test; use hello_world_test;'

before_install: phpenv config-add phpconfig.ini

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml
