<?php

$localization = [];
$localization[ 'launguages'] =  [
    'en' => '🇬🇧 English',
    'it' => '🇮🇹 Italiano',
    'de' => '🇩🇪 Deutsch',
    'ru' => '🇷🇺 Русский',
    'hi' => '🇮🇳 हिन्दी'
];
$localization['en'] = [
    'Bot_Title' => '📖 <b>MyAddressBookBot</b>™',
    'Welcome_Msg' =>  'Welcome to <b>MyAddressBookBot.</b>
You can add users and bots to your personal address book by saving only the <i>username</i>.
The username of the contacs saved by forward will be automatically updated.
All your contacts will be privately stored in a server and will never be shared.
Choose your language to start.',
    'Menu_Msg' => 'Welcome to <b>MyAddressBookBot.</b>
Adding a person or a bot is simple, just forward me a message from the user you want to store in the address book or tap <i>Add</i> to add them manually.
Contacs saved by forward will be automatically updated when they change username.
Tap one of the buttons below to start or press /help to get help on how to use me.',
    'About_Msg' => 'I have been created using php by @danyspin97, I\'m based on HadesWrapper and i\'m currently running in an Raspberry Pi3.
All your contacts will be privately stored in a server and will never be shared.
', // Put "Translated in 'insert this language' by "@yourusername" if you want to, optional
    'Help_Msg' => 'Tap /start to go to menu.
Forward me a message and i\'ll save the user who sent it.
Tap <i>Add</i> to manually add a contact to your address book.
Tap <i>Browse AddressBook</i> too see or search your contacts if you have any.
Tap <i>Options</i> you can change language, update usernames in your address book(doesn\'t work with contact added manually) or delete all your address book.
If the bot is stucked just click /start to restart it(you won\'t lose contacts neither settings).',
    'ChooseLanguage_Msg' => 'Choose your language by tapping one of the button below:',
    'AddUsername_Msg' => 'Forward me the message of the contact you want to save or send me the username in the form <pre>@username.</pre>',
    'AddFirstName_Msg' => 'Send me the <b>first name</b>.',
    'AddLastName_Msg' => 'Send me the <b>last name</b> or tap <i>skip</i>',
    'AddDescription_Msg' => 'Send me some notes about this contact that might help you remember who he is or tap <i>skip</i>.',
    'Options_Msg' => '<b>Avaiable options</b>:',
    'UsernameLenght_Msg' => 'The username must be between 5 to 32 characters long.',
    'DeleteASPrompt_Msg' => 'Are you sure you want to delete this contact from your address book?',
    'DeleteAllContactsPrompt_Msg' => 'Are you sure you want to delete all contacts from your address book?',
    'CheckPrivate_Msg' => 'Check the message in our private chat',
    'ContactAlreadyExist_Msg' => ' is already on your address book.',
    'ForwardAgain_Msg' => 'Forward another user to save or tap of the buttons below.',
    'ContactNotExist_Msg' => ' not exist in your address book.',
    'AddHisSelf_Msg' => 'You can\'t add yourself.',
    'DeleteAS_Msg' => 'This contact has been deleted.',
    'Username_Msg' => '<b>Username</b>: ',
    'FirstName_Msg' => '<b>First name</b>: ',
    'LastName_Msg' => '<b>Last name</b>: ',
    'Description_Msg' => '<b>Description</b>: ',
    'ResendUsername_Msg' => 'Please send me again the username in the form <pre>@username.</pre>',
    'Skipped_Msg' => '<i>skipped</i>',
    'EditUsername_Msg' => 'Send me the new <b>username</b>.',
    'EditFirstName_Msg' => 'Send me the new <b>first name</b>.',
    'EditLastName_Msg' => 'Send me the new <b>last name</b>.',
    'EditDescription_Msg' => 'Send me the new <b>description</b>.',
    'EditedUsername_Msg' => '<b>New username</b>: ',
    'EditedFirstName_Msg' => '<b>New first name</b>: ',
    'EditedLastName_Msg' => '<b>New last name</b>: ',
    'EditedDescription_Msg' => '<b>New description</b>: ',
    'DeletedLastName_Msg' => '<b>Last name deleted</b>.',
    'DeletedDescription_Msg' => '<b>Description deleted</b>.',
    'SaveContact_Msg' => 'Save this contact in your address book or edit it before saving',
    'AddressBookEmty_Msg' => 'Your address book is empty. First add someone by forwarding me a message from a user or tapping <i>Add</i>.',
    'NoUsername_Msg' => 'This user has no username!',
    'EnterSearchQuery_Msg' => 'Search for:',
    'ShowResults_Msg' => 'Show results for ',
    'ResultsNull_Msg' => 'There aren\'t any contacts that correspond to ',
    'Order_Msg' => 'Choose the order which your contacts will be listed.',
    'Add_Button' => 'Add ➕',
    'Options_Button' => 'Options ⚙',
    'Back_Button' => '↩️ Back',
    'Skip_Button' => 'Skip ⏩',
    'BrowseAB_Button' => 'Browse address book 📘',
    'Menu_Button' => 'Menu 🔘',
    'Language_Button' => 'Select Language 🌐',
    'UpdateUsername_Button' => 'Update username 🔄',
    'EditUsername_Button' => 'Edit username 📝',
    'EditFirstName_Button' => 'Edit first name 📝',
    'EditLastName_Button' => 'Edit last name 📝',
    'EditDescription_Button' => 'Edit description 📝',
    'Delete_Button' => 'Delete contact ➖',
    'AddLastName_Button' => 'Add last name ➕',
    'AddDescription_Button' => 'Add description ➕',
    'Cancel_Button' => 'Cancel ✖️',
    'Confirm_Button' => 'Continue ☑️',
    'DeleteLastName_Button' => 'Delete last name ➖',
    'DeleteDescription_Button' => 'Delete description ➖',
    'SaveFromInline_Button' => 'Save this contact',
    'Save_Button' => 'Save ➕',
    'Edit_Button' => 'Edit 📝',
    'Share_Button' => 'Share contact ↪️',
    'Search_Button' => 'Search 🔎',
    'BackToSearch_Button' => '↩️ Back to results',
    'SearchAgain_Button' => 'Search again 🔎',
    'NewSearch_Button' => 'New search 🔎',
    'UpdateAll_Button' => 'Update usernames 🔄',
    'DeleteAll_Button' => 'Delete contacts ❌',
    'Order_Button' => 'Select order #⃣',
    'FirstOrder_Button' => '1⃣ First name, last name',
    'SecondOrder_Button' => '2⃣ Last name, first name',
    'ThirdOrder_Button' => '3⃣ Username',
    'Vote_Button'=> 'Vote me!',
    'ContactAdded_AnswerCallback' => 'The contact has been added',
    'Registered_AnswerCallback' => 'Registered',
    'Options_AnswerCallback' => 'Here there are the options',
    'LastName_AnswerCallback' => 'Last name: ',
    'Description_AnswerCallback' => 'Description: ',
    'Skipped_AnswerCallback' => 'skipped',
    'LanguageChanged_AnswerCallback' => 'Language changed!',
    'SameLanguage_AnswerCallback' => 'Your language is already in english',
    'Saved_AnswerCallback' => 'Saved',
    'UsernameUpdated_AsnwerCallback' => 'Username updated ☑️',
    'UsernameAlreadyUpdated_AsnwerCallback' => 'Username already update',
    'ShowingContact_AsnwerCallback' => 'Showing: ',
    'UsernamesUpdated_AsnwerCallback' => 'Usernames updated ☑️',
    'AllContactsDeleted_AnswerCallback' => 'All contacts have been deleted',
    'NoContact_AnswerCallback' => 'You have no contacts',
    'Register_InlineQuery' => 'Create address book',
    'SwitchPM_InlineQuery' => 'Browse address book',
    'AddHisSelf_EasterEgg' => 'Don\'t you remember your name?',
    'Error' => 'Error, please contact @danyspin97.',
    'Language' => '🇬🇧 English',
    'it' => 'Italian',
    'es' => 'Spanish',
    'fr' => 'French',
    'de' => 'German',
    'pt' => '',
    'ru' => 'Russian',
    'fa' => 'Farsi(Persian)',
    'hi' => 'Hindi'
];
$localization['it'] = [
    'Bot_Title' => '📖 <b>MyAddressBookBot</b>',
    'Welcome_Msg' =>  'Benvenuto su <b>AddressBookBot.</b>
Puoi utilizzarmi per salvare gli utenti e i bot di telegram utilizzando solo il loro <i>username</i>.
Sarà automaticamente aggiornato l\'username dei contatti salvati attraverso l\'inoltro.
I tuoi contatti saranno salavati su un server in privato e non verrano mai condivisi.
Scegli la lingua per iniziare.',
    'Menu_Msg' => 'Benvenuto su <b>AddressBookBot.</b>
Aggiungere una persona è semplice, inoltrami il messaggio dell\' utente che vuoi aggiungere nella rubrica oppure premi su <i>Aggiungi</i> e segui le istruzioni.
Per iniziare premi uno dei pulsanti in basso oppure clicca /help per ricevere aiuto sull\'utilizzo del bot.',
    'Help_Msg' => 'Clicca /start per andare al menu.
Inoltrami un messaggio e salverò l\'utente che lo ha mandato.
Premi <i>Aggiungi</i> per aggiungere manualmente un utente alla rubrica.
Premi <i>Sfoglia rubrica</i> per sfogliare i tuoi contatti o fare una ricerca.
Premi <i>Opzioni</i> per cambiare la lingua, aggiornare gli username dei tuoi contatti(non funziona con i contatti aggiunti manualmente) o eliminare tutta la tua rubrica.
Se il bot si è bloccato stucked clicca /start per ripartire il bot(non perderai nè i contatti nè le impostazioni).',
    'About_Msg' => 'Sono stato creato da @danyspin97 utilizzando PHP e Postgresql.',
    'ChooseLanguage_Msg' => 'Scegli la tua lingua cliccando su uno dei pulsanti qui in basso:',
    'AddUsername_Msg' => 'Inoltrami il messaggio dell\'utente che vuoi salvare nella tua rubrica oppure inviami l\'username nella forma <pre>@username.</pre>',
    'AddFirstName_Msg' => 'Inviami il <b>nome</b>.',
    'AddLastName_Msg' => 'Inviami il <b>cognome</b> o premi <i>Salta</i>',
    'AddDescription_Msg' => 'Inviami una descrizione che possa aiutarti a ricordare chi sia questo contatto o premi <i>Salta</i>.',
    'Options_Msg' => '<b>Opzioni disponibili</b>:',
    'UsernameLenght_Msg' => 'L\'username deve essere lungo tr 5 e 32 caratteri.',
    'DeleteASPrompt_Msg' => 'Sei sicuro di voler cancellare questo contatto dalla tua rubrica?',
    'DeleteAllContactsPrompt_Msg' => 'Sei sicuro di voler cancellare tutti contatti dalla tua rubrica?',
    'CheckPrivate_Msg' => 'Controlla il messaggio nella chat privata',
    'ContactAlreadyExist_Msg' => ' è già presente nella tua rubrica.',
    'ForwardAgain_Msg' => 'Inoltrami il messaggio di un altro utente oppure premi uno dei pulsanti qui sotto.',
    'ContactNotExist_Msg' => ' non esiste nella tua rubrica.',
    'AddHisSelf_Msg' => 'Non puoi aggiungerti alla tua rubrica.',
    'DeleteAS_Msg' => 'Questo contatto è stato eliminato.',
    'Username_Msg' => '<b>Username</b>: ',
    'FirstName_Msg' => '<b>Nome</b>: ',
    'LastName_Msg' => '<b>Cognome</b>: ',
    'Description_Msg' => '<b>Descrizione</b>: ',
    'ResendUsername_Msg' => 'Inviami di nuovo l\'username nella forma <pre>@username.</pre>',
    'Skipped_Msg' => '<i>saltato</i>',
    'EditUsername_Msg' => 'Inviami il nuovo <b>username</b>.',
    'EditFirstName_Msg' => 'Inviami il nuovo <b>nome</b>.',
    'EditLastName_Msg' => 'Inviami il nuovo <b>cognome</b>.',
    'EditDescription_Msg' => 'Inviami la nuova <b>decrizione</b>.',
    'EditedUsername_Msg' => '<b>Nuovo username</b>: ',
    'EditedFirstName_Msg' => '<b>Nuovo nome</b>: ',
    'EditedLastName_Msg' => '<b>Nuovo cognome</b>: ',
    'EditedDescription_Msg' => '<b>Nuova descrizione</b>: ',
    'DeletedLastName_Msg' => '<b>Cognome eliminato</b>.',
    'DeletedDescription_Msg' => '<b>Descrizione eliminata</b>.',
    'SaveContact_Msg' => 'Salva questo contatto nella tua rubrica o modificalo prima di salvarlo',
    'AddressBookEmty_Msg' => 'Inizia aggiungendo contatti sulla tua rubrica',
    'NoUsername_Msg' => 'Questo utente non ha username!',
    'EnterSearchQuery_Msg' => 'Cerca:',
    'ShowResults_Msg' => 'Mostro i risultati per ',
    'ResultsNull_Msg' => 'Non ci sono contatti che corrispondono a ',
    'Order_Msg' => 'Scegli il modo in cui i contatti verrano ordinati.',
    'Add_Button' => 'Aggiungi ➕',
    'Options_Button' => 'Opzioni ⚙',
    'Back_Button' => '↩️ Indietro',
    'Skip_Button' => 'Salta ⏩',
    'BrowseAB_Button' => 'Sfoglia rubrica 📘',
    'Menu_Button' => 'Menu 🔘',
    'Language_Button' => 'Seleziona lingua 🌐',
    'UpdateUsername_Button' => 'Aggiorna username 🔄',
    'EditUsername_Button' => 'Modifica username 📝',
    'EditFirstName_Button' => 'Modifica nome 📝',
    'EditLastName_Button' => 'Modifica cognome 📝',
    'EditDescription_Button' => 'Modifica descrizione 📝',
    'Delete_Button' => 'Elimina utente ➖',
    'AddLastName_Button' => 'Aggiungi cognome ➕',
    'AddDescription_Button' => 'Aggiungi descrizione ➕',
    'Cancel_Button' => 'Annulla ✖️',
    'Confirm_Button' => 'Conferma ☑️',
    'DeleteLastName_Button' => 'Elimina cognome ➖',
    'DeleteDescription_Button' => 'Elimina descrizione ➖',
    'SaveFromInline_Button' => 'Salva questo contatto',
    'Save_Button' => 'Salva ➕',
    'Edit_Button' => 'Modifica 📝',
    'Share_Button' => 'Condividi contatto ↪️',
    'Search_Button' => 'Cerca 🔎',
    'BackToSearch_Button' => '↩️ Torna ai risultati',
    'SearchAgain_Button' => 'Cerca ancora 🔎',
    'NewSearch_Button' => 'Nuova ricerca 🔎',
    'UpdateAll_Button' => 'Aggiorna usernames 🔄',
    'DeleteAll_Button' => 'Elimina contatti ❌',
    'Order_Button' => 'Seleziona ordine #⃣',
    'FirstOrder_Button' => '1⃣ Nome, cognome',
    'SecondOrder_Button' => '2⃣ Cognome, nome',
    'ThirdOrder_Button' => '3⃣ Username',
    'Vote_Button'=> 'Votami!',
    'ContactAdded_AnswerCallback' => 'Il nuovo contatto è stato aggiunto',
    'Registered_AnswerCallback' => 'Registrato',
    'Options_AnswerCallback' => 'Ecco le opzioni',
    'LastName_AnswerCallback' => 'Cognome: ',
    'Description_AnswerCallback' => 'Descrizione: ',
    'Skipped_AnswerCallback' => 'saltato',
    'LanguageChanged_AnswerCallback' => 'Lingua cambiata',
    'SameLanguage_AnswerCallback' => 'La lingua è già impostata su italiano',
    'Saved_AnswerCallback' => 'Salvato',
    'UsernameUpdated_AsnwerCallback' => 'Username aggiornato',
    'UsernameAlreadyUpdated_AsnwerCallback' => 'Username già aggiornato',
    'ShowingContact_AsnwerCallback' => 'Mostrando: ',
    'UsernamesUpdated_AsnwerCallback' => 'Username aggiornati',
    'AllContactsDeleted_AnswerCallback' => 'Tutti i contatti sono stati eliminati',
    'NoContact_AnswerCallback' => 'Non hai contatti nella rubrica',
    'Register_InlineQuery' => 'Crea rubrica',
    'SwitchPM_InlineQuery' => 'Sfoglia rubrica',
    'AddHisSelf_EasterEgg' => 'Non riesci a ricordarti il tuo nome?',
    'Error' => 'Errore, per favore contattare @danyspin97.',
    'Language' => '🇮🇹 Italiano',
    'en' => 'Inglese',
    'es' => 'Spagnolo',
    'fr' => 'Francese',
    'de' => 'Tedesco',
    'ru' => 'Russo',
    'fa' => 'Persiano',
    'hi' => 'Hindi'
];
$localitzation['fr'] = [
    'Bot_Title' => '<b>MyAddressBookBot</b>',
    'Welcome_Msg' =>  'Bienvenue à <b> MyAddressBookBot</b>.
Vous pouvez ajouter des utilisateurs et les bots à votre carnet d\'adresses personnel en enregistrant seulement le <i>nom d\'utilisateur</i>.
Le nom d\'utilisateur des Contacs enregistrés par l\'attaquant sera automatiquement mis à jour.
Tous vos contacts seront enregistrés en privé dans un serveur et ne seront jamais partagées.
Choisissez votre langue pour commencer.',
    'Menu_Msg' => 'Bienvenue à <b> MyAddressBookBot.</b>
Ajout d\'une personne ou à un bot est simple, envoyer juste moi un message de l\'utilisateur que vous souhaitez stocker dans le carnet d\'adresses ou appuyez sur <i>Ajouter</i> pour les ajouter manuellement.
Contacs sauvés par l\'avant seront automatiquement mis à jour quand ils changent le nom d\'utilisateur.
Appuyez sur un des boutons ci-dessous pour commencer ou appuyez sur / aide pour obtenir de l\'aide sur la façon de me utiliser.',
    'About_Msg' => 'I have been created using php by @danyspin97, I\'m based on HadesWrapper and i\'m current running in an Raspberry Pi3.
Tous vos contacts seront enregistrés en privé dans un serveur et ne seront jamais partagées.', // Put "Translated in 'insert this language' by @yourusername" if you want to, optional
    'Help_Msg' => 'Tapez /start pour passer au menu.
Transférez-moi un message et je vais mettre l\'utilisateur qui l\'a envoyé.
Tapez <i>ajouter</i> pour ajouter un contact à votre carnet d\'adresses.
Tapez <i>voir carnet d\'adresses</i> pour voir vos contacts si vous avez une ou de rechercher dans vos contacts.
Appuyez sur <i> Options </ i> vous pouvez changer la langue, mettre à jour les noms d\'utilisateur dans votre carnet d\'adresses (ce ne fonctionne pas avec le contact ajouté manuellement) ou de supprimer tout votre carnet d\'adresses.
Si le bot est coincé cliquez /start à redémarrer (vous ne perdrez pas de contacts ni les paramètres).',
    'ChooseLanguage_Msg' => 'Choisissez votre langue en appuyant sur un des boutons ci-après:',
    'AddUsername_Msg' => 'Transférez-moi un message du contact que vous souhaitez enregistrer ou envoyez-moi le nom d\'utilisateur sous la forme @username.',
    'AddFirstName_Msg' => 'Envoyez-moi le prénom.',
    'AddLastName_Msg' => 'Envoyez-moi le nom ou appuyez sur <i>sauter</i>.',
    'AddDescription_Msg' => 'Envoyez-moi quelques remarques à propos de ce contact qui pourrait aider à vous rappeler qui il est ou appuyez <i>sauter</i>.',
    'Options_Msg' => '<b>Possible options</b>:',
    'UsernameLenght_Msg' => 'Le nom d\'utilisateur doit �tre entre 5 et 32 caractères.',
    'DeleteASPrompt_Msg' => 'Etes-vous sûr de vouloir effacer cette contact de votre carnet d\'adresses?',
    'DeleteAllContactsPrompt_Msg' => 'Êtes-vous sûr de vouloir supprimer tous les contacts de votre carnet d\'adresses?',
    'CheckPrivate_Msg' => 'Vérifiez le message dans notre chat privé',
    'ContactAlreadyExist_Msg' => ' est déjà dans votre carnet d\'adresses. Essayez d\'envoyer un autre utilisateur ou transmettre son message',
    'ForwardAgain_Msg' => 'Forward another user to save or tap of the buttons below.',
    'ContactNotExist_Msg' => ' n\'existe pas dans votre carnet d\'adresses.',
    'AddHisSelf_Msg' => 'Vous ne pouvez pas ajouter vous-même.',
    'DeleteAS_Msg' => 'Ce contact a été supprimé.',
    'Username_Msg' => '<b>Nom d\'utilisateur</b>: ',
    'FirstName_Msg' => '<b>Prénom</b>: ',
    'LastName_Msg' => '<b>Nom de famille</b>: ',
    'Description_Msg' => '<b>La description</b>: ',
    'ResendUsername_Msg' => 'S\'il vous plaît renvoyez-moi le nom d\'utilisateur en la forme <pre>@username.</pre>',
    'Skipped_Msg' => '<i>sautée</i>',
    'EditUsername_Msg' => 'Envoyez-moi le nouveau <b>nom d\'utilisateur</b>.',
    'EditFirstName_Msg' => 'Envoyez-moi le nouveau <b>pr�nom</b>.',
    'EditLastName_Msg' => 'Envoyez-moi le nouveau <b>nom</b>.',
    'EditDescription_Msg' => 'Envoyez-moi le nouveau <b>description</b>.',
    'EditedUsername_Msg' => '<b>Nouveau nom d\'utilisateur</b>: ',
    'EditedFirstName_Msg' => '<b>Nouveau pr�nom</b>: ',
    'EditedLastName_Msg' => '<b>New last name</b>: ',
    'EditedDescription_Msg' => '<b>Nouveau nom</b>: ',
    'DeletedLastName_Msg' => '<b>Nom effacer</b>.',
    'DeletedDescription_Msg' => '<b>Description effacer</b>.',
    'SaveContact_Msg' => 'Enregistrer ce contact dans votre carnet d\'adresses ou modifier lui avant d\'enregistrer',
    'AddressBookEmty_Msg' => 'Votre carnet d\'adresses est vide. Tout d\'abord ajouter quelqu\'un en transmettant un message d\'un utilisateur ou en tapant <i>Ajouter</i>.',
    'NoUsername_Msg' => 'Cet utilisateur n\'a pas le nom d\'utilisateur!',
    'EnterSearchQuery_Msg' => 'Rechercher:',
    'ShowResults_Msg' => 'Afficher les r�sultats pour ',
    'ResultsNull_Msg' => 'Il n\'y a pas de contact qui correspondent à ',
    'Order_Msg' => 'Choose the order which your contacts will be listed.',
    'Add_Button' => 'Ajouter',
    'Options_Button' => 'Options',
    'Back_Button' => '<- Retourner',
    'Skip_Button' => 'Passer',
    'BrowseAB_Button' => 'Voir Carnet d\'adresses',
    'Menu_Button' => 'Afficher le menu',
    'Language_Button' => 'Langue',
    'EditUsername_Button' => 'Modifier le nom d\'utilisateur',
    'EditFirstName_Button' => 'Modifier le prénom',
    'EditLastName_Button' => 'Modifier le nom',
    'EditDescription_Button' => 'Modifier la description',
    'Delete_Button' => 'Effacer le contact',
    'AddLastName_Button' => 'Ajouter un nom',
    'AddDescription_Button' => 'Ajouter une description',
    'Cancel_Button' => 'Annuler',
    'Confirm_Button' => 'Continuer',
    'DeleteLastName_Button' => 'Effacer le nom',
    'DeleteDescription_Button' => 'Effacer la description',
    'SaveFromInline_Button' => 'Enregistrer ce contact',
    'Save_Button' => 'Enregistrer',
    'Edit_Button' => 'Modifier',
    'Share_Button' => 'Partager le contact',
    'Search_Button' => 'Chercher🔎',
    'BackToSearch_Button' => 'Retour aux résultats',
    'SearchAgain_Button' => 'Search again 🔎',
    'NewSearch_Button' => 'New search 🔎',
    'UpdateAll_Button' => 'Update usernames 🔄',
    'DeleteAll_Button' => 'Delete contacts ❌',
    'Order_Button' => 'Select order #⃣',
    'FirstOrder_Button' => '1⃣ First name, last name',
    'SecondOrder_Button' => '2⃣ Last name, first name',
    'ThirdOrder_Button' => '3⃣ Username',
    'Vote_Button'=> 'Vote me!',
    'ContactAdded_AnswerCallback' => 'Le contact a été ajouté',
    'Registered_AnswerCallback' => 'Inscrit',
    'Options_AnswerCallback' => 'Ici, il y a les options',
    'LastName_AnswerCallback' => 'Nom de famille: ',
    'Description_AnswerCallback' => 'La description: ',
    'Skipped_AnswerCallback' => 'sautée',
    'LanguageChanged_AnswerCallback' => 'Langue changé!',
    'SameLanguage_AnswerCallback' => 'Votre langue est déjà en français',
    'Saved_AnswerCallback' => 'Enregistré',
    'UsernameUpdated_AsnwerCallback' => 'Username updated ☑️',
    'UsernameAlreadyUpdated_AsnwerCallback' => 'Username already update',
    'ShowingContact_AsnwerCallback' => 'Showing: ',
    'UsernamesUpdated_AsnwerCallback' => 'Usernames updated ☑️',
    'AllContactsDeleted_AnswerCallback' => 'All contacts have been deleted',
    'NoContact_AnswerCallback' => 'You have no contacts',
    'Register_InlineQuery' => 'Cr�er carnet d\'adresses',
    'SwitchPM_InlineQuery' => 'Afficher carnet d\'adresses',
    'AddHisSelf_EasterEgg' => 'Vous ne vous rappelez votre nom?',
    'Error' => 'Erreur, s\'il vous pla�t contacter @kingdragonx.',
    'Language' => 'Français',
    'it' => 'Italien',
    'en' => 'Anglais',
    'de' => 'Allemand',
    'pt' => '',
    'ru' => 'Russe',
    'fa' => 'Farsi (Persan)',
    'hi' => 'Hindi'
];
$localization['ru'] = [
    'Bot_Title' => '<b>MyAddressBookBot</b>',
    'Welcome_Msg' =>  'Добро пожаловать в <b>твою записную книгу MyAddressBookBot.</b>
Ты можешь добавить пользователя или бота в свою личную записную книгу, сохранив только его <i>никнейм</i>.
Я буду автоматически обновлять никнеймы контактов, сохраненных по пересланному сообщению.
Все твои контакты будут надежно сохранены на сервере и никогда не будут доступны другим пользователям.
Выбери язык для начала работы.',
    'Menu_Msg' => 'Добро пожаловать в <b>твою записную книгу MyAddressBookBot.</b>
Добавить пользователя или бота легко: просто перешли мне сообщение от пользователя, которого хочешь сохранить, или нажми кнопку <i>Добавить</i>, чтобы создать запись вручную.
Я буду автоматически обновлять никнеймы контактов, сохраненных по пересланному сообщению, если они сменят свой никнейм.
Нажми на одну из кнопок ниже, чтобы начать или напиши /help чтобы узнать, как пользоваться мной. ',
    'About_Msg' => 'Я был создан с помощью PHP и Postgresql. Создатель: @danyspin97.
Все твои контакты будут надежно сохранены на сервере и никогда не будут доступны другим пользователям.
Перевел на русский: @phash.',
    'Help_Msg' => 'Нажми /start чтобы перейти в меню.
Перешли мне сообщение, и я сохраню его отправителя.
Нажми <i>Добавить</i> чтобы добавить контакт вручную.
Нажми <i>Показать записную книгу</i> для получения списка контактов и поиска серди них.
Нажми <i>Настройки</i> чтобы поменять язык, обновить никнеймы контактов (не работает с контактами, добавленными вручную) или удалить все свои контакты.
Если я завис, просто жми /start, чтобы перезапустить меня (настройки и контакты не потеряются).',
    'ChooseLanguage_Msg' => 'Выберите язык, нажав на одну из кнопок ниже:',
    'AddUsername_Msg' => 'Перешли мне сообщение и я сохраню его отправителя. Или отправь мне его никнейм в формате <pre>@username.</pre>',
    'AddFirstName_Msg' => 'Отправь мне имя.',
    'AddLastName_Msg' => 'Отправь мне фамилию или нажми <i>пропустить</i>',
    'AddDescription_Msg' => 'Отправь мне заметку об этом контакте, которая поможет вспомнить, кто это. Если не хочешь - нажми <i>пропустить</i>.',
    'Options_Msg' => '<b>Доступные настройки:</b>:',
    'UsernameLenght_Msg' => 'Имя пользователя должно состоять из 5-32 символов.',
    'DeleteASPrompt_Msg' => 'Ты уверен, что хочешь удалить этот контакт из записной книги?',
    'DeleteAllContactsPrompt_Msg' => 'Ты уверен, что хочешь удалить все контакты из записной книги?',
    'SaveContact_Msg' => 'Сохранить контакт или отредактировать данные?',
    'CheckPrivate_Msg' => 'Отправил тебе в личные сообщения.',
    'ContactAlreadyExist_Msg' => ' уже есть в записной книге.',
    'ForwardAgain_Msg' => 'Перешли сообщение другого пользователя, чтобы сохранить его, или нажми на одну из кнопок ниже.',
    'ContactNotExist_Msg' => ' отсутствует в записной книге.',
    'AddHisSelf_Msg' => 'Нельзя добавить себя в записную книгу.',
    'DeleteAS_Msg' => 'Этот контакт был удален.',
    'Username_Msg' => '<b>Никнейм</b>: ',
    'FirstName_Msg' => '<b>Имя</b>: ',
    'LastName_Msg' => '<b>Фамилия</b>: ',
    'Description_Msg' => '<b>Заметка</b>: ',
    'ResendUsername_Msg' => 'Пожалуйста, отправь мне еще раз никнейм в формате <pre>@username.</pre>',
    'Skipped_Msg' => '<i>пусто</i>',
    'EditUsername_Msg' => 'Отправь мне новый <b>никнейм</b>.',
    'EditFirstName_Msg' => 'Отправь мне новое <b>имя</b>.',
    'EditLastName_Msg' => 'Отправь мне новую <b>фамилию</b>.',
    'EditDescription_Msg' => 'Отправь мне новую <b>заметку</b>.',
    'EditedUsername_Msg' => '<b>Новый никнейм</b>: ',
    'EditedFirstName_Msg' => '<b>Новое имя</b>: ',
    'EditedLastName_Msg' => '<b>Новая фамилия</b>: ',
    'EditedDescription_Msg' => '<b>Новая заметка</b>: ',
    'DeletedLastName_Msg' => '<b>Фамилия удалена</b>.',
    'DeletedDescription_Msg' => '<b>Заметка удалена</b>.',
    'AddressBookEmty_Msg' => 'Для начала добавь контакты в записную книгу',
    'NoUsername_Msg' => 'У этого пользователя не задан никнейм!',
    'EnterSearchQuery_Msg' => 'Введите посковый запрос:',
    'ShowResults_Msg' => 'Результаты по запросу ',
    'ResultsNull_Msg' => 'Контакты не найдены по запросу ',
    'Order_Msg' => 'Выбери порядок сортировки контактов',
    'Add_Button' => 'Добавить ➕',
    'Options_Button' => 'Настройки ⚙',
    'Back_Button' => '↩️ Назад',
    'Skip_Button' => 'Пропустить ⏩',
    'BrowseAB_Button' => 'Показать записную книгу 📘',
    'Menu_Button' => 'Показать меню 🔘',
    'Language_Button' => 'Язык 🌐',
    'UpdateUsername_Button' => 'Обновить ниенейм 🔄',
    'EditUsername_Button' => 'Редактировать никнейм 📝',
    'EditFirstName_Button' => 'Редактировать имя 📝',
    'EditLastName_Button' => 'Редактировать фамилию 📝',
    'EditDescription_Button' => 'Редактировать заметку 📝',
    'Delete_Button' => 'Удалить контакт ➖',
    'AddLastName_Button' => 'Добавить фамилию ➕',
    'AddDescription_Button' => 'Добавить заметку ➕',
    'Cancel_Button' => 'Отменить ✖️',
    'Confirm_Button' => 'Продолжить ☑️',
    'DeleteLastName_Button' => 'Удалить фамилию ➖',
    'DeleteDescription_Button' => 'Удалить заметку ➖',
    'SaveFromInline_Button' => 'Сохранить этот контакт',
    'Save_Button' => 'Сохранить ➕',
    'Edit_Button' => 'Редактировать 📝',
    'Share_Button' => 'Поделиться контактом',
    'Search_Button' => 'Поиск🔎',
    'BackToSearch_Button' => '↩️ Назад к поиску',
    'SearchAgain_Button' => 'Искать снова🔎',
    'NewSearch_Button' => 'Новый поиск 🔎',
    'UpdateAll_Button' => 'Обновить никнеймы 🔄',
    'DeleteAll_Button' => 'Удалить контакты ❌',
    'Order_Button' => 'Выбери порядок сортировки #⃣',
    'FirstOrder_Button' => '1⃣ Имя, фамилия',
    'SecondOrder_Button' => '2⃣ Фамилия, имя',
    'ThirdOrder_Button' => '3⃣ Никнейм',
    'Vote_Button' => 'Vote me!',
    'ContactAdded_AnswerCallback' => 'Контакт был добавлен',
    'Registered_AnswerCallback' => 'Зарегистрирован',
    'Options_AnswerCallback' => 'Доступные настройки',
    'LastName_AnswerCallback' => 'Фамилия: ',
    'Description_AnswerCallback' => 'Подробности: ',
    'Skipped_AnswerCallback' => 'Пропускаем...',
    'LanguageChanged_AnswerCallback' => 'Язык изменен!',
    'SameLanguage_AnswerCallback' => 'Русский язык уже выбран.',
    'Saved_AnswerCallback' => 'Сохранено',
    'UsernameUpdated_AsnwerCallback' => 'Никнейм обновлен',
    'UsernameAlreadyUpdated_AsnwerCallback' => 'Никнейм уже обновлен',
    'ShowingContact_AsnwerCallback' => 'Показываю: ',
    'UsernamesUpdated_AsnwerCallback' => 'Никнеймы обновлены',
    'AllContactsDeleted_AnswerCallback' => 'Все контакты были удалены',
    'NoContact_AnswerCallback' => 'У тебя ни одного контакта',
    'Register_InlineQuery' => 'Создать записную книжку',
    'SwitchPM_InlineQuery' => 'Показать записную книжку',
    'AddHisSelf_EasterEgg' => 'Не можешь запомнить свой ник?',
    'Error' => 'Возникла ошибка, пожалуйста, сообщите о ней @danyspin97.',
    'Language' => '🇷🇺 Русский',
    'it' => 'Итальянский',
    'es' => 'Испанский',
    'fr' => 'Французский',
    'de' => 'Немецкий',
    'en' => 'Английский',
    'fa' => 'Арабский',
    'hi' => 'Хинди'
];
$localization['de'] = [
    'Bot_Title' => '<b>MyAddressBookBot</b>',
    'Welcome_Msg' =>  'Willkommen zu <b>MyAddressBookBot.</b>
Du kannst Nutzer und Bots zu deinem eigenen Adressbuch hinzufügen indem du den <i>Benutzernamen</i> speicherst. Die Nutzernamen deiner durch weiterleiten hinzugefügten Kontakte werden automatisch aktualisiert. Alle deine Kontakte werden privat auf dem Server gespeichert und an niemanden weitergegeben.',
    'Menu_Msg' => 'Willkommen zu <b>MyAddressBookBot.</b>
Eine Person oder einen Bot hinzuzufuegen ist einfach. Senden Sie mir eine Nachricht des Kontakts, den du speichern willst oder tippe auf <i>Hinzufügen</i> um sie manuell hinzuzufügen.
Kontakte die du durch weiterleiten einer Nachricht hinzugefügt hast werden automatisch aktualisiert wenn sie ihren Nutzernamen ändern.
Tippe auf einen der Knöpfe um zu starten oder drücke auf /help um Hilfe anzuzeigen.',
    'About_Msg' => 'Ich wurde mit Hilfe von php von @danyspin97 erstellt. Ich basiere auf HadesWrapper und  momentan kann man mich im Raspberry Pi3 vorfinden.
Alle deine Kontakte werden privat gespeichert und nie weitergegeben.',
    'Help_Msg' => 'Drücke /start um zum Menü zu kommen.
Leite eine Nachricht weiter und ich werde den Absender speichern.
Drücke <i>Hinzufügen</i> um manuell einen Kontakt zu deinem Adressbuch hinzuzufügen.
Drücke <i>Zeige Addressbuch</i> um deine Kontakte zu sehen oder durchsuchen, falls du welche hast.
Drücke <i>Optionen</i> um die Sprache zu ändern, die Nutzernamen zu aktualisieren (funktioniert nicht mit manuell hinzugefügten Kontakten) oder dein gesamtes Adressbuch zu löschen.
Wenn der Bot nicht reagiert drücke auf /start um den bot neu zu starten (Weder Kontakte noch Einstellungen gehen dabei verlohren).',
    'ChooseLanguage_Msg' => 'Wähle deine Sprache indem du unten auf den Knopf drückst:',
    'AddUsername_Msg' => 'Sende mir die Nachricht von dem Kontakt den du speichern willst oder den Benutzernamen wie folgt @username.',
    'AddFirstName_Msg' => 'Sende mir den Vornamen.',
    'AddLastName_Msg' => 'Sende mir den Nachnamen oder drücke <i>uberspringen</i>',
    'AddDescription_Msg' => 'Sende mir einige Informationen über den Kontakt, welche dir helfen dich an ihn zu erinnern oder drücke <i>überspringen</i>.',
    'Options_Msg' => '<b>Verfügbare Optionen</b>:',
    'UsernameLenght_Msg' => 'Der Benutzername muss 5-32 Zeichen lang sein.',
    'DeleteASPrompt_Msg' => 'Bist du dir sicher, dass du diesen Kontakt aus deinem Adressbuch entfernen möchtest?',
    'DeleteAllContactsPrompt_Msg' => 'Are you sure you want to delete all contacts from your address book?',
    'SaveContact_Msg' => 'Speichere diesen Kontakt in deinem Adressbuch oder bearbeite ihn in dem du einen der folgenden Knöpfe drückst',
    'CheckPrivate_Msg' => 'Lese die Nachricht in unserem Privatchat',
    'ContactAlreadyExist_Msg' => ' befindet sich bereits in dem Adressbuch.',
    'ForwardAgain_Msg' => 'Forward another user to save or tap of the buttons below.',
    'ContactNotExist_Msg' => ' nicht vorhanden in deinem Adressbuch.',
    'AddHisSelf_Msg' => 'Du kannst dich nicht selbst hinzufügen.',
    'DeleteAS_Msg' => 'Dieser Kontakt wurde gelöscht.',
    'Username_Msg' => '<b>Benutzername</b>: ',
    'FirstName_Msg' => '<b>Vorname</b>: ',
    'LastName_Msg' => '<b>Nachname</b>: ',
    'Description_Msg' => '<b>Beschreibung</b>: ',
    'ResendUsername_Msg' => 'Schicke mir bitte erneut den Benutzernamen wie folgt <pre>@username.</pre>',
    'Skipped_Msg' => '<i>überspringen</i>',
    'EditUsername_Msg' => 'Schicke mir den neuen <b>Benutzernamen</b>.',
    'EditFirstName_Msg' => 'Schicke mir den neuen <b>Vornamen</b>.',
    'EditLastName_Msg' => 'Schicke mir den neuen <b>Nachnamen</b>.',
    'EditDescription_Msg' => 'Schicke mir die neue <b>Beschreibung<b>/.',
    'EditedUsername_Msg' => '<b>Mein neuer Benutzername</b>: ',
    'EditedFirstName_Msg' => '<b>Neuer Vorname</b>: ',
    'EditedLastName_Msg' => '<b>Neuer Nachname</b>: ',
    'EditedDescription_Msg' => '<b>Neue Beschreibung</b>: ',
    'DeletedLastName_Msg' => '<b>Nachname entfernt</b>.',
    'DeletedDescription_Msg' => '<b>Beschreibung entfernt</b>.',
    'SaveContact_Msg' => 'Speichere diesen Kontakt in deinem Adressbuch oder bearbeite ihn vor dem abspeichern',
    'AddressBookEmty_Msg' => 'Füge zunächst einige Kontakte deinem Adressbuch hinzu',
    'NoUsername_Msg' => 'Dieser Benutzer hat keinen Benutzernamen!',
    'EnterSearchQuery_Msg' => 'Suche nach:',
    'ShowResults_Msg' => 'Zeige Ergebnisse f?r ',
    'ResultsNull_Msg' => 'Es sind keine Kontakte vorhanden die folgendem entsprechen ',
    'Order_Msg' => 'Wähle die Reihenfolge in welcher deine Kontakte angezeigt werden.',
    'Add_Button' => 'Hinzufügen ➕',
    'Options_Button' => 'Optionen ⚙',
    'Back_Button' => '↩️ Zurück',
    'Skip_Button' => 'Überspringen ⏩',
    'BrowseAB_Button' => 'Adressbuch durchsuchen 📘',
    'Menu_Button' => 'Menü 🔘',
    'Language_Button' => 'Sprache auswählen 🌐',
    'UpdateUsername_Button' => 'Username aktualisieren 🔄',
    'EditUsername_Button' => 'Bearbeite Benutzernamen 📝',
    'EditFirstName_Button' => 'Bearbeite Vornamen 📝',
    'EditLastName_Button' => 'Bearbeite Nachnamen 📝',
    'EditDescription_Button' => 'Bearbeite Beschreibung 📝',
    'Delete_Button' => 'Entferne Kontakt ➖',
    'AddLastName_Button' => 'Füge Nachnamen hinzu ➕',
    'AddDescription_Button' => 'Füge Beschreibung hinzu ➕',
    'Cancel_Button' => 'Abbrechen ✖️',
    'Confirm_Button' => 'Fortsetzen ☑️',
    'DeleteLastName_Button' => 'Entferne Nachnamen ➖',
    'DeleteDescription_Button' => 'Entferne Beschreibung ➖',
    'SaveFromInline_Button' => 'Speichere diesen Kontakt',
    'Save_Button' => 'Speichern ➕',
    'Edit_Button' => 'Bearbeiten 📝',
    'Share_Button' => 'Kontakt teilen ↪️',
    'Search_Button' => 'Suchen 🔎',
    'BackToSearch_Button' => '↩️ Zurück zu Ergebnis',
    'SearchAgain_Button' => 'Nocheinmal suchen 🔎',
    'NewSearch_Button' => 'Neue Suche 🔎',
    'UpdateAll_Button' => 'Usernamen aktualisieren 🔄',
    'DeleteAll_Button' => 'Kontakte löschen ❌',
    'Order_Button' => 'Wähle Ordnung #⃣',
    'FirstOrder_Button' => '1⃣ Vorname, Nachname',
    'SecondOrder_Button' => '2⃣ Nachname, Vorname',
    'ThirdOrder_Button' => '3⃣ Nutzername',
    'Vote_Button' => 'Vote me!',
    'ContactAdded_AnswerCallback' => 'Der Kontakt wurde hinzugefügt',
    'Registered_AnswerCallback' => 'registriert',
    'Options_AnswerCallback' => 'Hier sind die Möglichkeiten',
    'LastName_AnswerCallback' => 'Nachname: ',
    'Description_AnswerCallback' => 'Beschreibung: ',
    'Skipped_AnswerCallback' => 'ausgelassene',
    'LanguageChanged_AnswerCallback' => 'Sprachänderung!',
    'SameLanguage_AnswerCallback' => 'Deine Sprache ist bereits Englisch',
    'Saved_AnswerCallback' => 'Gespeichert',
    'UsernameUpdated_AsnwerCallback' => 'Username updated',
    'UsernameAlreadyUpdated_AsnwerCallback' => 'Username already update',
    'ShowingContact_AsnwerCallback' => 'Angezeigt: ',
    'UsernamesUpdated_AsnwerCallback' => 'Nutzernamen aktualisiert',
    'AllContactsDeleted_AnswerCallback' => 'Alle Kontakte wurden gelöscht',
    'NoContact_AnswerCallback' => 'Du hast keine Kontakte',
    'Register_InlineQuery' => 'Erstelle Adressbuch',
    'SwitchPM_InlineQuery' => 'Zeige Adressbuch',
    'AddHisSelf_EasterEgg' => 'Hast du deinen Namen vergessen?',
    'Error' => 'Ein Fehler ist aufgetaucht, bitte wende dich an @danyspin97.',
    'Language' => '🇩🇪 Deutsch',
    'it' => 'Italienisch',
    'es' => 'Spanisch',
    'fr' => 'Französisch',
    'en' => 'Englisch',
    'ru' => 'Russisch',
    'fa' => 'Farsi(Persisch)',
    'hi' => 'Hindi'
];
$localization['hi'] = [
    'Bot_Title' => '<b>माई अड्रेस बुक बोट</b>',
    'Welcome_Msg' => '  स्वागत है आपका <b>माई अड्रेस बुक बोट</b> में। केवल <i>यूज़रनेम</i> संग्रक्षित कर के आप किसी भी व्यक्ति एवं बोट को अपने अड्रेस बुक में आसानी से डाल सकते हैं। जो यूज़र नेम फॉरवर्ड के द्वारा भेजे जाएंगे वो स्वयं ही अपडेट हो जाएंगे। सारी जानकारी एक सर्वर में संग्रक्षित रहेगी तथा कभी भी किसी के भी साथ बांटी नही जायेगी। शुरू करने के लिए भाषा चुने।',
    'Menu_Msg' => 'स्वागत है आपका <b> माई अड्रेस बुक बोट </b> में। किसी व्यक्ति या बोट को संग्रक्षित करना है आसान। जिस भी व्यक्ति को आप संग्रक्षित करना चाहते हैं, मुझे उसके द्वारा भेजा हुआ कोई भी एक संदेश भेजें। अथवा स्वयं संग्रक्षित करने हेतू <i> एड </i> चुनें। यदि उस व्यक्ति ने अपना यूज़र नेम बदला जिसे फॉरवर्ड के द्वारा संग्रक्षित किया गया है तो वह नाम स्वयं ही अपडेट हो जाएगा । शुरू करने के लिए नीचे दिए गए बटन में से कोई एक चुनें, या फिर मुझे प्रयोग करने की जानकारी के लिए /मदद को चुनें।',
    'About_Msg' => 'मेरी रचना php की सहायता से @danyspin97 के द्वारा की गयी है। मैं HadesWrapper पे आधारित हूँ तथा अभी Raspberry Pi3 में चल रहा हूँ।',
    'Help_Msg' => 'मेनू पे जाने के लिए /शुरू को चुनें। मुझे एक संदेश भेजें, और मैँ उस व्यक्ति को संग्रक्षित कर लूंगा जिसने आपको वो संदेश भेजा है। किसी व्यक्ति को स्वयं अपने अड्रेस बुक मे संग्रक्षित करने हेतू <i> एड </i> चुनें। यदि आप किसी व्यक्ति को अपनी अड्रेस बुक मे ढूंढना चाहते हैं तो <i>अड्रेस बुक देखें</i> को चुनें।  <i>ऑप्शन</i> को चुन के आप भाषा बदल सकते हैं, अड्रेस बुक में किसी व्यक्ति का यूज़र नेम बदल सकते हैं (यह सेवा उसके लिए काम नही करेगी जिस व्यक्ति को आपने स्वयं अड्रेस बुक में संग्रक्षित किया है) या फिर अपनी पूरी अड्रेस बुक को मिटा अथवा डिलीट कर सकते हैं। यदि बोट अटक जाये य काम करना बंद कर दे तो /शुरू को चुनें (आपके संग्रक्षित सेटिंग या व्यक्ति दोनो ही सुरक्षित रहेंगे)।',
    'ChooseLanguage_Msg' => 'भाषा बदलने के लिए निम्न दिए गए बटन में से एक चुनें।:',
    'AddUsername_Msg' => 'जिस व्यक्ति को आप संग्रक्षित करना चाहते हैं, उसका भेजा हुआ संदेश या यूज़र नेम मुझे @username के रूप में भेजें।',
    'AddFirstName_Msg' => 'मुझे प्रथम नाम भेजें',
    'AddLastName_Msg' => 'मुझे आखरी नाम भेजें अथवा <i>स्किप</i> चुनें',
    'AddDescription_Msg' => 'इस व्यक्ति के बारे में कुछ जानकारी लिखें ताकि आपको स्मरण रहे की वो कौन है, अथवा <i>स्किप</i> चुनें।',
    'Options_Msg' => '<b>मौजूदा ऑपशन्स</b>:',
    'UsernameLenght_Msg' => 'यूज़र नेम 5-32 अक्षर के बीच होना चाहिए।',
    'DeleteASPrompt_Msg' => 'क्या आप वाकई इस व्यक्ति को अड्रेस बुक से मिटाना चाहते हैं?',
    'DeleteAllContactsPrompt_Msg' => 'क्या आप सच मे सारे नाम अपनी अड्रेस बुक से मिटाना चाहते हैं?',
    'SaveContact_Msg' => 'इस व्यक्ति को अपने अड्रेस बुक में संग्रक्षित करने के लिए या बदलाव लाने के लिए निम्न बटन में से एक चुनें। ',
    'CheckPrivate_Msg' => 'एकल चैट में संदेश को देखें।',
    'ContactAlreadyExist_Msg' => 'यह व्यक्ति आपकी अड्रेस बुक में पहले से ही संग्रक्षित है। दूसरे व्यक्ति को संग्रक्षित करने के लिए चुनें।',
    'ForwardAgain_Msg' => 'एक और व्यक्ति को संग्रक्षित करने हेतू यहाँ फॉरवर्ड करें या फिर नीचे दिए गए बटनों में से एक चुनें।',
    'ContactNotExist_Msg' => ' यह व्यक्ति आपकी अड्रेस बुक में उपस्थित नहीँ है।',
    'AddHisSelf_Msg' => 'आप स्वयं को संग्रक्षित नही कर सकते।.',
    'DeleteAS_Msg' => 'इस व्यक्ति को मिटाया जा चुका है।',
    'Username_Msg' => '<b>यूज़र नेम</b>: ',
    'FirstName_Msg' => '<b>प्रथम नाम </b>: ',
    'LastName_Msg' => '<b>अंतिम नाम</b>: ',
    'Description_Msg' => '<b>जानकारी</b>: ',
    'ResendUsername_Msg' => 'कृपया मुझे यूज़र नेम फिर से निम्न तरीके से भेजें। <pre>@यूज़र नेम</pre>',
    'Skipped_Msg' => '<i>छोड़ दें</i>',
    'EditUsername_Msg' => 'मुझे नया <b>यूज़र नेम</b> भेजें।',
    'EditFirstName_Msg' => 'मुझे नया प्रथम नाम <b>प्रथम नाम</b> भेजें',
    'EditLastName_Msg' => 'मुझे नया अंतिम नाम <b>अंतिम नाम</b> भेजें।',
    'EditDescription_Msg' => 'मुझे नई जानकारी <b>जानकारी<b>/ भेजें।',
    'EditedUsername_Msg' => '<b>नया यूज़र नेम</b>: ',
    'EditedFirstName_Msg' => '<b>नया प्रथम नाम</b>: ',
    'EditedLastName_Msg' => '<b>नया अंतिम नाम</b>: ',
    'EditedDescription_Msg' => '<b>नई जानकारी</b>: ',
    'DeletedLastName_Msg' => '<b>अंतिम नाम मिटाया गया</b>.',
    'DeletedDescription_Msg' => '<b>जानकारी मिटाई गई</b>.',
    'SaveContact_Msg' => 'इस व्यक्ति को अपनी अड्रेस बुक में संग्रक्षित करें अथवा संग्रक्षित करने के पूर्व आवश्यक बदलाव लाएं।',
    'AddressBookEmty_Msg' => 'शुरू करने के लिए सर्वप्रथम कुछ लोगों को अपने अड्रेस बुक मे संग्रक्षित करें।',
    'NoUsername_Msg' => 'इस व्यक्ति का कोई यूज़र नेम नहीं है!',
    'EnterSearchQuery_Msg' => 'खोजें:',
    'ShowResults_Msg' => 'खोज का परिणाम ',
    'ResultsNull_Msg' => 'इस खोज का कोई परिणाम नही, कोई इस नाम का उपस्थित नहीं। ',
    'Order_Msg' => 'जिस प्रकार से संग्रक्षित नाम आप देखना चाहते हैं, वह प्रकार चुनें।',
    'Add_Button' => 'ऐड ➕',
    'Options_Button' => 'ऑपशन ⚙',
    'Back_Button' => '↩️ पीछे जाएं',
    'Skip_Button' => 'छोड़ें ⏩',
    'BrowseAB_Button' => 'अड्रेस बुक दिखाएँ 📘',
    'Menu_Button' => 'मेनू दिखाएँ 🔘',
    'Language_Button' => 'भाषा 🌐',
    'UpdateUsername_Button' => 'यूज़र नेम अपडेट करें 🔄',
    'EditUsername_Button' => 'यूज़र नेम बदलें 📝',
    'EditFirstName_Button' => 'प्रथम नाम बदलें 📝',
    'EditLastName_Button' => 'अंतिम नाम बदलें 📝',
    'EditDescription_Button' => 'जानकारी बदलें 📝',
    'Delete_Button' => 'मिटायें ➖',
    'AddLastName_Button' => 'अंतिम नाम जोड़ें ➕',
    'AddDescription_Button' => 'जानकारी जोड़ें ➕',
    'Cancel_Button' => 'कैंसल ✖️',
    'Confirm_Button' => 'जारी रखें ☑️',
    'DeleteLastName_Button' => 'अंतिम नाम मिटायें ➖',
    'DeleteDescription_Button' => 'जानकारी मिटायें ➖',
    'SaveFromInline_Button' => 'इस व्यक्ति को संग्रक्षित करें',
    'Save_Button' => 'संग्रक्षित करें ➕',
    'Edit_Button' => 'बदलाव लाएं 📝',
    'Share_Button' => 'शेयर करें ↪️',
    'Search_Button' => 'ढूंढें 🔎',
    'BackToSearch_Button' => '↩️ वापिस परिणाम पे जाएं',
    'SearchAgain_Button' => 'फिर से ढूंढे 🔎',
    'NewSearch_Button' => 'New search 🔎',
    'UpdateAll_Button' => 'सारे यूज़र नेम अपडेट करें 🔄',
    'DeleteAll_Button' => 'संग्रक्षित व्यक्ति को डिलीट करें ❌',
    'Order_Button' => 'ऑडर चुनें #⃣',
    'FirstOrder_Button' => '1⃣ प्रथम नाम, अंतिम नाम',
    'SecondOrder_Button' => '2⃣ अंतिम नाम, प्रथम नाम',
    'ThirdOrder_Button' => '3⃣ यूज़र नेम',
    'Vote_Button' => 'मुझे वोट दें।',
    'ContactAdded_AnswerCallback' => 'इस व्यक्ति को संग्रक्षित कर लिया गया है।',
    'Registered_AnswerCallback' => 'रजिस्टर',
    'Options_AnswerCallback' => 'ये ऑप्शन तालिका है',
    'LastName_AnswerCallback' => 'अंतिम नाम: ',
    'Description_AnswerCallback' => 'जानकारी: ',
    'Skipped_AnswerCallback' => 'छोड़ दिया गया',
    'LanguageChanged_AnswerCallback' => 'भाषा बदल दी गई!',
    'SameLanguage_AnswerCallback' => 'आपकी चुनी हुई भाषा हिन्दी है।',
    'Saved_AnswerCallback' => 'संग्रक्षित',
    'UsernameUpdated_AsnwerCallback' => 'यूज़र नेम अपडेट हो गया',
    'UsernameAlreadyUpdated_AsnwerCallback' => 'यूज़र नेम पहले ही अपडेट हो चुका है',
    'ShowingContact_AsnwerCallback' => 'अभी दिख रहा: ',
    'UsernamesUpdated_AsnwerCallback' => 'यूज़र नेम अपडेट हो चुका है',
    'AllContactsDeleted_AnswerCallback' => 'सारे संग्रक्षित व्यक्ति डिलीट हो चुके',
    'NoContact_AnswerCallback' => 'कोई भी व्यक्ति आपके अड्रेस बुक मे संग्रक्षित नहीं',
    'Register_InlineQuery' => 'अड्रेस बुक बनाएं',
    'SwitchPM_InlineQuery' => 'अड्रेस बुक दिखाएँ',
    'AddHisSelf_EasterEgg' => 'क्या आपको अपना नाम याद नहीं?',
    'Error' => 'एरर, कृपया @danyspin97 से संपर्क करें।',
    'Language' => '🇮🇳 हिन्दी',
    'it' => 'इटालियन',
    'es' => 'स्पेनिश',
    'fr' => 'फ्रेंच',
    'de' => 'जर्मन',
    'ru' => 'रूसी',
    'fa' => 'फारसी',
    'en' => 'अंग्रेज़ी'
];
